### ISSUE TITLE
Screen Design

### ISSUE THREAD

**Issue by Finneah** [Finneah/butler#2]
# Welche Screens gibt es?

- [ ]  Detailscreen #3 
- [ ] Jahresübersicht #4 
- [ ] Anlegen / Bearbeiten #5 
- [ ] Startscreen für den ersten App Start #6 
- [ ] Screen für das "unterstützte" Bearbeiten von Einträgen #7

**Comment by Dakiira** [comment]
Mir ist aufgefallen das wir eventuell noch einen Screen für das erste Öffnen der App brauchen. Da gibt es ja noch keine Daten die wir anzeigen können

**Comment by Finneah** [comment]
> Mir ist aufgefallen das wir eventuell noch einen Screen für das erste Öffnen der App brauchen. Da gibt es ja noch keine Daten die wir anzeigen können

Da hast du recht.Ist ja jetzt nicht mehr die Jahresübersicht.

Wie wäre es wenn wir beim ersten App Start direkt eine art geführtes Anlegen des ersten Eintrages machen. Also du bist in einem extra Screen der aussieht wie der ANlegen/Bearbeiten Screen und hier kannst du aber nicht weg navigieren. Und wir helfen mit Tooltip (oder Tutorial wie bei heppiventcard) beim Anlegen. Danach landet man auf der Monatsübersicht.

**Comment by Finneah** [comment]
Oder wirklich nur die Monatsübersicht und da steht dann eben "Es sind noch keine Einträge vorhanden" Wäre das einfachste. Allerdings geht das dann nicht so schön mit dem Tutorial. Von daher ja, weiterer Screen. Guter Gedanke.

**Comment by Finneah** [comment]
Also ich favorisieren auf jedenfall Nativebase 3.0
Aber hier findest du Templates für  v1.2.0
https://github.com/GeekyAnts/NativeBase-Sketch-Template

**Comment by Dakiira** [comment]
https://www.figma.com/file/VThTMpew2nAuSZUzyISKAP/nativebase-v1-2-0?node-id=4%3A2543
