### ISSUE TITLE
Detailscreen

### ISSUE THREAD

**Issue by Finneah** [Finneah/butler#3]
# Beschreibung
DIeser Screen soll der Startscreen sein. Hier wird der aktuelle Monat bzw der gewählte Monat angezeigt. 
Es gibt zwei Ansichtsoptionen: Übersicht und Liste. 
Bei beiden Ansichten können neue Einträge angelegt werden. 
Bei der Ansicht Übersicht kann auf die einzelnen Einträge geklickt werden zum Bearbeiten. 
Von hier aus soll zur Jahresübersicht Navigiert werden können.

## Tabs
Dies soll als Tab oben dargestellt werden.
Dies kann z.B. mit dem Element "Tabs" von https://docs.nativebase.io/tabs erstellt werden. 
Die Übersicht ist dabei vorausgewählt

### Übersicht
- Diagramm der Ausgaben https://github.com/JesperLekland/react-native-svg-charts

### Liste
Auflistung der einzelnen Einnahmen / Ausgaben
Sortierung: 
1. Einnahmen
2. Ausgaben
- Fixkosten
- variable Kosten
3. Rest
4. Evtl eine Progressbar unten?

## Navigation Jahresübersicht
Entweder wir nehmen ein Icon rechts im Header. z.B. Das KalenderIcon oder das Liste Icon um zur Jahresübersicht zu navigieren 
Oder wir verwenden ein BottomTab.

**Comment by Finneah** [comment]
![Uploading 23E1C542-4495-4402-BFE5-6A507CE5BED6.png…]()

**Comment by Dakiira** [comment]
Header

-  Monatsanzeige
-  Bei Klick auf Monatanzeige öffnet sich Monatsauswahl (mit picker)

Übersicht mit Header + Peil:
Einnahmen
Ausgaben
Rest

--> bei klick auf element öffnet sich neuer Screen

Pie Chart nach Kategorien (erstmal):
- Bei Klick auf eintrag kategorie + wert


Auflistung
-  Fixkosten (nur ein paar) --> auf gleichen Screen wie oben
-  Andere Kosten (nur ein paar) --> auf gleichen Screen wie oben

**Comment by Finneah** [comment]
![Uploading 61D1F137-025E-4DDA-AE1E-77BF885F290C.jpeg…]()
